[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/recuperar.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
